import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/desktopfifteen">DesktopFifteen</Link>
        </li>
        <li>
          <Link to="/register">Register</Link>
        </li>
        <li>
          <Link to="/">Login</Link>
        </li>
        <li>
          <Link to="/transactions">Transactions</Link>
        </li>
        <li>
          <Link to="/customers">Customers</Link>
        </li>
        <li>
          <Link to="/policiestwo">PoliciesTwo</Link>
        </li>
        <li>
          <Link to="/policiesone">PoliciesOne</Link>
        </li>
        <li>
          <Link to="/policiesthree">PoliciesThree</Link>
        </li>
        <li>
          <Link to="/policies">Policies</Link>
        </li>
        <li>
          <Link to="/transactionsindex">Transactionsindex</Link>
        </li>
        <li>
          <Link to="/beneficiariesindex">Beneficiariesindex</Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/transactionsfilter">TransactionsFilter</Link>
        </li>
        <li>
          <Link to="/policiesindex">Policiesindex</Link>
        </li>
        <li>
          <Link to="/frame355">Frame355</Link>
        </li>
        <li>
          <Link to="/dashboardaddbeneficiary">DashboardAddbeneficiary</Link>
        </li>
        <li>
          <Link to="/policiesdetailspage">PoliciesDetailspage</Link>
        </li>
        <li>
          <Link to="/beneficiariesone">BeneficiariesOne</Link>
        </li>
        <li>
          <Link to="/beneficiariestwo">BeneficiariesTwo</Link>
        </li>
        <li>
          <Link to="/transactionsone">TransactionsOne</Link>
        </li>
        <li>
          <Link to="/transactionsfilterone">TransactionsFilterOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
